name: custom

on: [push]

jobs:
  app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - run: ./gradlew app:assembleDebug
      - uses: actions/upload-artifact@v3
        with:
          name: app-debug-unsigned
          path: app/build/outputs/apk/debug/app-debug.apk
  release:
    name: Sign
    runs-on: ubuntu-latest
    environment: custom
    needs:
      - app
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-debug-unsigned
      - name: Write keystore
        run: echo "$KEYSTORE_BASE64" | base64 --decode > "$KEYSTORE_PATH"
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Sign APK
        run: $ANDROID_HOME/build-tools/33.0.0/apksigner sign --ks "$KEYSTORE_PATH" --ks-pass env:KEYSTORE_PASSWORD --in app-debug.apk --out app-debug-signed.apk
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Verify APK signature
        run: $ANDROID_HOME/build-tools/33.0.0/apksigner verify --print-certs app-debug-signed.apk
      - uses: actions/upload-artifact@v3
        with:
          name: app-debug-signed
          path: app-debug-signed.apk
